### ISSUE TITLE
Mask mode only works in certain orientations.

### ISSUE THREAD

**Issue by Bolt7** [theripper93/Better-Roofs#1]
All doors are open.
Looking out (for reference)
![image](https://user-images.githubusercontent.com/75871317/120240005-8aa02500-c22d-11eb-85e3-6099fa1127a4.png)
Looking in from east (can only see past the south door)
![image](https://user-images.githubusercontent.com/75871317/120240081-b7543c80-c22d-11eb-8dfa-b3493ee15281.png)
Looking in from south (can only see past the east door)
![image](https://user-images.githubusercontent.com/75871317/120240127-d357de00-c22d-11eb-96dc-7dcc8eebfd9b.png)
Looking in from west (doesn't function at all)
![image](https://user-images.githubusercontent.com/75871317/120240178-eff41600-c22d-11eb-8920-0b6008e5ce87.png)
Looking in from north (doesn't function at all)
![image](https://user-images.githubusercontent.com/75871317/120240217-0601d680-c22e-11eb-983e-57a1534f6545.png)

**Comment by theripper93** [comment]
1: is the tale NOT in roof mode?
2: did you wall off the edges of the map

**Comment by Bolt7** [comment]
Edges are walled off. Tile is in roof mode (you can see that the cutout works in images 2 and 3).
I've tested without the module, and there are also some (but not exaclty the same) differences depending on orientation, so it might not be on your end.
When you set up a similar situation, does this not occur for you?

**Comment by theripper93** [comment]
not really, can you ping me on discord so i can take a closer look through screen share? Also, per instruction the tile should NOT be in roof mode but FADE. test with that

**Comment by Bolt7** [comment]
Fade mode (my bad for not reading instructions) helped, but didn't fix everything. Now it's like the original screenshots, except the issue of only seeing past one other door is no longer there (now it works completely as intended 2 & 3), and 4 & 5 act as expected, except for not showing any roof. Additionaly, I was using Fog-of-War, which seems to cause some of the issues, but that's a separate thing so from now on I'll have that disabled. Updated images:
![image](https://user-images.githubusercontent.com/75871317/120256297-cfdb4b80-c25b-11eb-96ac-4acd8de2a83b.png)
![image](https://user-images.githubusercontent.com/75871317/120256323-dcf83a80-c25b-11eb-954a-1b5280a26a90.png)
![image](https://user-images.githubusercontent.com/75871317/120256348-eaadc000-c25b-11eb-9cec-63cf59c5124e.png)
![image](https://user-images.githubusercontent.com/75871317/120256376-f8fbdc00-c25b-11eb-9a07-a2c7a74b238f.png)
![image](https://user-images.githubusercontent.com/75871317/120256395-02854400-c25c-11eb-9b11-c1cb0e94e403.png)
I might be able to screen share tomorrow, but it's late in my time zone now (ET), so not now.
The only issue remaining seems to also exist in core (not showing the tile when north or west of it), so I'm not sure how much you'll be able to do.

**Comment by theripper93** [comment]
yep, that's a core issue if you are close to the tile, nothing i can do about that unfortunately, gonna consider the issue closed!
