### ISSUE TITLE
Token visible on every level

### ISSUE THREAD

**Issue by mvanduijvenvoorde** [theripper93/Better-Roofs#11]
I use multiple complete tiles on top of eachother to create levels.

Now I have tokens on level 1 for instance, except the token is visible (with +10ft on top of it) on EVERY level. Any idea what I'm doing wrong?:

![foundryvtt_levels](https://user-images.githubusercontent.com/70683364/127147910-f0bb7dfb-6310-49f6-ba06-b9ebc3652ad3.png)

Setup example:
![skyreach_castle_floor_0](https://user-images.githubusercontent.com/70683364/127147813-139c0d1c-49fc-4d4d-8245-708376db0b16.jpg)
![skyreach_castle_floor_1](https://user-images.githubusercontent.com/70683364/127147817-a1400125-2263-4af3-816f-e85223d3c76a.jpg)

**Comment by mvanduijvenvoorde** [comment]
Here with the tokens
![foundryvtt_levels_tokens](https://user-images.githubusercontent.com/70683364/127148055-6d7313f6-f161-49e9-93b1-04d8bd20b3f0.png)

**Comment by theripper93** [comment]
The git is for bug reports for help on setting up maps use the discord
