### ISSUE TITLE
Better Roofs errors on scenes that have token vision disabled

### ISSUE THREAD

**Issue by manuelVo** [theripper93/Better-Roofs#14]
On scenes where token vision is disabled, selecting a token that has the setting "Has vision" enabled will cause Better Roofs to fail with the following error:

![Error message caused by better roofs](https://user-images.githubusercontent.com/1705157/129066445-bec0446d-2b98-4455-a7eb-c3b7935daf3d.png)

**Comment by theripper93** [comment]
is there any other repercussion? if not i'll simply add a return if token vision is disabled

**Comment by manuelVo** [comment]
The API call `getFloorsForPoint` of the Levels module yields incorrect values in the same constellatiin. I'm not sure if that's related though.

**Comment by theripper93** [comment]
same constellation?

**Comment by theripper93** [comment]
(fixed br issue in next release)
