### ISSUE TITLE
[Question/Suggestion] Entire Tile reveals when only a small portion visible

### ISSUE THREAD

**Issue by Shuggaloaf** [theripper93/Better-Roofs#15]
Hi I'm guessing what is seen in the pic below is a bug but thought I'd ask 1st if it is intended behavior? 

If it is intended, I'd like to request/suggest that only what is in the token's line of sight be visible. In other words, basically like real life, if I see a tiny bit of my neighbors house through the window, I wouldn't know the entire shape of their home. 

If this is intended for some purpose I just haven't figured out yet, maybe the option to toggle view styles would be nice.

Otherwise, great mod, thanks for all the work on this and others recently!

------
Foundry 0.8.8; BR 0.9.9.1; Win10; Tested with Electron app and Chrome 

Tile Setting:
<img src="https://user-images.githubusercontent.com/79543184/131251542-c1326a30-caab-49f4-82bb-0118e45ee2ad.png" width="50%">

Entire 2nd roof is visible when only a small sliver should be able to be seen. Tile correctly goes back to unseen what token moves out of window line of sight:
<img src="https://user-images.githubusercontent.com/79543184/131251563-bc08945c-a6dd-4247-bfa7-2a8ca1d1e68f.png" width="50%">

**Comment by theripper93** [comment]
Not really a bug, it’s just how the system behaves, adding additional masks to have it work how you are asking would not only have performance impact but also has some technical issues ok with masks on masks that are not easy to solve, if I ever find a solution I’ll consider adding it

**Comment by Shuggaloaf** [comment]
OK so the system is treating the tile differently than others because of the way the applied mask works. I see what you're saying. I could see that definitely leading to some issues if each one in view has to calculate. Especially if in view of several roofs. Makes sense and thanks for considering it for the future if you can get a fix.

**Comment by theripper93** [comment]
The problem is that the los does not intersect with the roof so I cannot use it as a mask. If you enable the foundry sight rays debug you’ll see what I mean
