### ISSUE TITLE
Need help with Settings or the Configuration

### ISSUE THREAD

**Issue by Talaren** [theripper93/Better-Roofs#2]
Hello,
I drew a house, then created the walls in Foundry, also doors and windows, then the roof on top.
But unfortunately it does not work, can you please help me what it could be?
Thanks a lot for this.

Greetings Talaren

Browser: Brave V1.25.70
![Screenshot 2021-06-10 203313](https://user-images.githubusercontent.com/3872571/121579247-d58b1b00-ca2b-11eb-9425-782e1389173c.jpg)
![Screenshot 2021-06-10 203511](https://user-images.githubusercontent.com/3872571/121579262-d8860b80-ca2b-11eb-9777-e90f39484bfb.jpg)

Browser: Firefox 84.0b8 (64-Bit)
![Screenshot 2021-06-10 204216](https://user-images.githubusercontent.com/3872571/121579830-62ce6f80-ca2c-11eb-9fe1-244369fc23be.jpg)

Settings Walls / Doors / Windows
![Screenshot 2021-06-10 204630](https://user-images.githubusercontent.com/3872571/121580385-f869ff00-ca2c-11eb-98c2-1ed0152a2e47.jpg)

**Comment by theripper93** [comment]
please use the discord for this kind of issues https://discord.gg/F53gBjR97G - i'll gladly help there
