### ISSUE TITLE
Better-Roofs modes not working as expected

### ISSUE THREAD

**Issue by TurtleShark2910** [theripper93/Better-Roofs#22]
I am experiencing some odd behavior from the better-roofs module. I tried looking through already opened tickets to see if someone has had this issue, especially because I am _inclined to be believe it is user error_ (sorry) and I am missing a checkbox somewhere, but could not find anything.

**Environment**
Foundry 0.8.9
Better-Roofs 1.3.3
Lib-Wrapper 1.10.8.0
SFRPG System 0.14.3

_All additional modules disabled_

**Steps**
Enabled "Advanced Settings" in Better-Roofs module settings
Created scene with "Token Vision" and "Fog of War Exploration"
I set a building with interior and external walls. Marked external wall for the appropriate walls.
Walled off the entire map with the GUI button.
Placed Roof tile as an overhead tile.
Set better-roofs mode to "Show"
Set occlusion mode to "Fade"
Defined Polygon since it had not picked up the external walls correctly.

**Expected Behavior**
Overhead tile should show through fog of war

**Actual Behavior**
View of tile is blocked behind external walls:
![image](https://user-images.githubusercontent.com/83877927/142881360-c42f9d4f-0ab6-4f02-a975-3e6ad92e6e87.png)
![image](https://user-images.githubusercontent.com/83877927/142881417-764598b2-bf18-455f-abe9-307e31c7a4d8.png)

**Steps taken to fix**
Updated from version 1.3.2 to 1.3.3 today. Same behavior
Disabled all modules except Better-Roofs (and dependency). Same behavior

**Comment by theripper93** [comment]
Does the token have vision? BR needs vision to compute it's operations

**Comment by TurtleShark2910** [comment]
Yes, I do have vision set. Here are my vision settings for the token in the image:

![image](https://user-images.githubusercontent.com/83877927/142892322-826accc1-f306-438b-b111-547082f1862d.png)

**Comment by theripper93** [comment]
Would you mind continue troubleshooting in my discord channel, it's way easier for me https://discord.gg/F53gBjR97G

**Comment by theripper93** [comment]
moved to discord
