### ISSUE TITLE
[FEATURE] Setting for opacity of hidden roof (for GM with no tokens selected)

### ISSUE THREAD

**Issue by pesky-wobbit** [theripper93/Better-Roofs#24]
Love the module! But, as a GM, I am greatly distracted by the semi-translucent rooftops once gameplay has moved indoors. Works great when tokens are selected - roofs are completely invisible. I wish I could completely hide them when no tokens are selected. If there is a way to do this already, my apologies.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
