### ISSUE TITLE
Feature Request: Hide on mouseover

### ISSUE THREAD

**Issue by Co0nmz** [theripper93/Better-Roofs#29]
Hey there!

It would be really cool to be able to check a box to add the option to hide a roof on mouseover, if a token below the roof is selected.
This is useful for maps with many roofs such as a dense forest etc.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
