### ISSUE TITLE
Better Roofs not loading at all

### ISSUE THREAD

**Issue by jaanvaks** [theripper93/Better-Roofs#31]
**I have disabled all other modules: **True
**Module(s) **Better Roofs
**Conflicting Module(s) **
**Foundry and System version **Foundry 11.313 Dragonbane 1.4.0
Something to note is that I'm running Swedish localization of foundry.
(My guess is that this is the issue.)
**OS, Hosting, Browser (if applicable) **Ubuntu 23.04 lxc container in proxmox, My own server, Google chrome Version 117.0.5938.149 (Official Build) (arm64) on Mac
**Short description of bug **the module doesn't load, none of the UI shows up or any configuration for it
**Simple steps to reproduce the bug **

Start a new world with dragonbane, enable better roofs and the mandatory module.

**Screenshots and/or Console Errors**
![Screenshot 2023-10-13 at 21 19 57](https://github.com/theripper93/Better-Roofs/assets/11598505/304a1241-50f8-453d-b57e-5c68d7d481eb)

**Comment by jaanvaks** [comment]
I just testet restarting foundry in English and it still didn't work.
So that wasn't the issue.

**Comment by theripper93** [comment]
Can you show this “missing UI” ? Did you try reinstalling the module? Honestly I have strong doubts this is a bug

**Comment by jaanvaks** [comment]
I'm starting to suspect the same.
I saw a tutorial of this addon and that tutorial didn't specify what what part of what addon.
The addons I was missing was levels and wall Height.
I'm sorry for bothering you.
