### ISSUE TITLE
Problem with Vision (Token Field of View)

### ISSUE THREAD

**Issue by Maradeurfv** [theripper93/Better-Roofs#32]
Hello, today I had to notice that the "Vision (Token Field of View) no longer works for tiles that are defined as overhead and roof. The tile is no longer displayed. See attachment. Levels and wallheight are installed.
![Screenshot 2023-12-30 122435](https://github.com/theripper93/Better-Roofs/assets/146621810/a28a7cb7-d3d5-4aa0-adc0-63639cae2af7)
![Screenshot 2023-12-30 122409](https://github.com/theripper93/Better-Roofs/assets/146621810/9a8c68ca-e77a-487e-8fe3-fc20ad06ba01)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
