### ISSUE TITLE
Mask mode intersects oddly with invisible walls and open doors

### ISSUE THREAD

**Issue by Hydrall** [theripper93/Better-Roofs#5]
It seems as though, with Better Roofs enabled and Mask Mode activated, invisible walls are treated like normal walls when it comes to viewing beneath the mask.

![image](https://user-images.githubusercontent.com/14931056/122649290-2caf8080-d0fb-11eb-98b4-57921aa12d13.png)
With invisible wall

![image](https://user-images.githubusercontent.com/14931056/122649301-39cc6f80-d0fb-11eb-83d5-4a61d4a9ed52.png)
Without invisible wall

![image](https://user-images.githubusercontent.com/14931056/122649372-83b55580-d0fb-11eb-91ce-a9f16e02b906.png)
How my walls are set up, as well

Would be useful if it could distinguish so I could put windows my players can't just wander their way through.

Edit: It also seems to apply to open doors, as well.

**Comment by theripper93** [comment]
![image](https://user-images.githubusercontent.com/1346839/122656808-6796d000-d15e-11eb-9e2a-ca916b20b9c5.png)
