### ISSUE TITLE
Fog of War revealing incorrectly

### ISSUE THREAD

**Issue by lee1121** [theripper93/Better-Roofs#6]
Hello folks, I’ve been playing around with Better Roofs and unfortunately run into an issue: when exploring one layer, it also reveals the fog of war on other layers.

Example with pictures:
![image](https://user-images.githubusercontent.com/14054775/123182551-ffaef500-d48f-11eb-9fab-8c4390913c32.png)
Here my test PC is standing next to a fortified wall.
<br />

![image](https://user-images.githubusercontent.com/14054775/123182570-0b9ab700-d490-11eb-8460-15ab4ffefaf9.png)
Using the stairs, he walks up the wall.
<br />

![image](https://user-images.githubusercontent.com/14054775/123182581-105f6b00-d490-11eb-9557-4d4b85fabd45.png)
And when he gets back down, the fog of war below the wall is revealed.
<br />

![image](https://user-images.githubusercontent.com/14054775/123182595-15241f00-d490-11eb-89a0-7008305c52dd.png)
This are the current Overhead settings (though I have tried multiple different ones).

I hope that either I'm making a mistake or that this is a fixable issue, because this looks like a very promising module though not revealing the fog of war is a necessity for my campaign and it would be quite a bummer if I cannot use it.

Thanks in advance :)

**Comment by theripper93** [comment]
this is related to levels, not better roofs, but did you try the advanced fog of war setting?

**Comment by lee1121** [comment]
Oops, sorry about that.
Also, I had not realised the advanced fog of war existed.
I have now tried it and it unfortunately doesn't seem to have changed anything

**Comment by theripper93** [comment]
then it's probably something wrong in the setup. if you are at 10 elevation (on top of the bridge) it should hide the bridge in the fow

**Comment by lee1121** [comment]
Correction, it seems to work one-way. When revealing things on the wall, it shows through on the ground layer, but not the other way around. It may work if I put my background layer also as a tile.
Gonna test this right now

**Comment by theripper93** [comment]
yes if the background is also a tile with elevation set it will hide it, keep in mind that it won't save the fog exploration this way

**Comment by lee1121** [comment]
Oh, you're saying it won't save the fog exploration for players between sessions when doing that?

**Comment by theripper93** [comment]
no, in general, the fog in foundry cannot be multilayered, for this reason the workaround i have is just "disabling fog exploration" for that level

**Comment by lee1121** [comment]
That's a really big shame. Fog exploration is quite important in my campaign and my players won't like it when they have to keep re-exploring previously explored places.

Thank you very much for the help though!
