### ISSUE TITLE
Full visible map + Explorable/Undetectable building with walls

### ISSUE THREAD

**Issue by odhinn33** [theripper93/Better-Roofs#7]
Hi, great module! Would it be possible to have a full town map with all visible roofs/streets/everything... and by the time I enter a door... walls and sight are activated (closed rooms are hidden)...
The problem is that I have a couple of buildings players can explore... and if they have projected shadows with sight activated... they spot them quickly! And I don't want to trace contour of every town building! Am I missing something?

**Comment by theripper93** [comment]
you could disable the advanced fog if i'm understanding correctly what you are saying

**Comment by theripper93** [comment]
oh wait i think i know what you are saying, the answer is not really, at least it's way outside the scope of levels. You have to trace all the buildings unfortunatelly, scratch the previous comment

**Comment by odhinn33** [comment]
Yes sure, you mean Foundry VTT Discord, module-discussion channel, right? Anyway, thanks for your answer.
